Ajustes de termos e tradução
OpenBanking-Brasil/specs-seguranca pull request #115
Opened 2021-06-16 15:02 UTC by ediemerson-br

2021-06-16 15:06 UTC, ediemerson-br commented on aspsp-user-guide-ptbr.md
> +* Solicitar feedback com antecedência e com frequência, reconhecer que serão necessárias várias iterações para desenvolver um padrão conforme definido pelos processos da Organização Mundial do Comérc
Está correto citar a Organização Mundial do Comércio neste item?

2021-06-16 15:07 UTC, ediemerson-br commented on aspsp-user-guide-ptbr.md
> +* **Customer Friendly Name** - Será exibido aos clientes pelas instituições receptoras, e já deve ser reconhecido pelos clientes do banco.
Estes itens estão com o termo em inglês ou português no Diretório?

2021-06-16 15:08 UTC, ediemerson-br commented on aspsp-user-guide-ptbr.md
> +* **Notification WebHook** - *Authorization Servers* podem registrar um WebHook que receberá atualizações por push sobre as alterações dos participantes, seus softwares ou certificados.
Estes itens estão com o termo em inglês ou português no Diretório?

2021-06-16 22:17 UTC, ginglass commented on aspsp-user-guide-ptbr.md
> +* Solicitar feedback com antecedência e com frequência, reconhecer que serão necessárias várias iterações para desenvolver um padrão conforme definido pelos processos da Organização Mundial do Comérc
Removeria essa referência. Pararia em "um padrão".

2021-06-17 12:52 UTC, joaorodolfo commented on aspsp-user-guide-ptbr.md
> +* **Notification WebHook** - *Authorization Servers* podem registrar um WebHook que receberá atualizações por push sobre as alterações dos participantes, seus softwares ou certificados.
Ok, os termos estão de acordo com os campos listados no diretório em PT-br e tbm em EN.

2021-06-17 13:04 UTC, ediemerson-br commented on tpp-user-guide-ptbr.md
> +Consulte a especificação do Diretório OpenAPI v3 para o conjunto completo de endpoints disponíveis.
Esta especificação realmente existe?

2021-06-17 13:15 UTC, ediemerson-br commented
No item 1.4.1 do TPP Guide temos: 

"1.4.1 Sandbox {#Sandbox}
(...)
O Diretório suporta vários certificados, tipos de chave e um comando e configuração openssl será disponibilizado como um exemplo."

Eu não encontrei o tal exemplo no documento. Isto está correto?

2021-06-17 13:26 UTC, leo0x1d requested changes

2021-06-17 13:26 UTC, leo0x1d commented on aspsp-user-guide-ptbr.md
> +As regras exatas e os requisitos legais para cada função em um setor específico formam um framework de confiança ('Trust Framework'). Cada ecossistema requer um conjunto padronizado de regras e requi
```suggestion
As regras exatas e os requisitos legais para cada função em um setor específico formam um framework de confiança ('Trust Framework'). Cada ecossistema requer um conjunto padronizado de regras e requisitos legais que abrangem todas as funções e obrigações das interações acima. A combinação de quem fornece qual(is) função(ões), os níveis aos quais eles devem desempenhar essas funções e os padrões pelos quais essas operações devem ser realizadas podem ser definidas por um framework de confiança específico do setor.
```

2021-06-17 13:27 UTC, joaorodolfo commented on tpp-user-guide-ptbr.md
> +Consulte a especificação do Diretório OpenAPI v3 para o conjunto completo de endpoints disponíveis.
Sim, aqui: https://openbanking-brasil.github.io/areadesenvolvedor/#fase-2-apis-do-open-banking-brasil

2021-06-17 14:08 UTC, ginglass commented on aspsp-user-guide-ptbr.md
> +As regras exatas e os requisitos legais para cada função em um setor específico formam um framework de confiança ('Trust Framework'). Cada ecossistema requer um conjunto padronizado de regras e requi
O exemplo do comando openssl é exibido quando o usuário segue na interface de cadastro de certificados para emissão de um SSA. Não tenho acesso, mas percebi em uma apresentação esse step na configuração.

2021-06-17 20:18 UTC, merged