Fix#118 - auth constraints based on consent attributes
OpenBanking-Brasil/specs-seguranca pull request #157
Opened 2021-07-08 14:21 UTC by ginglass

- Created ID2 to security profile
- Added auth constraints based on consent attributes and expected error code

2021-07-08 15:24 UTC, RalphBragg requested changes

2021-07-08 15:24 UTC, RalphBragg commented on open-banking-brasil-financial-api-1_ID2-ptbr.md
> +    # (open-banking-brasil-financial-api-1_ID1)
Draft numbers need to change

2021-07-08 15:24 UTC, RalphBragg commented on open-banking-brasil-financial-api-1_ID2-ptbr.md
> +    # Open Banking Brasil Financial-grade API Security Profile 1.0 Implementers Draft 1
Draft number needs to change

2021-07-08 15:24 UTC, RalphBragg commented on open-banking-brasil-financial-api-1_ID2-ptbr.md
> +    title = "Open Banking Brasil Financial-grade API Security Profile 1.0 Implementers Draft 1"
Draft is 2

2021-07-08 15:24 UTC, RalphBragg commented on open-banking-brasil-financial-api-1_ID2-ptbr.md
> +    value = "open-banking-brasil-financial-api-1_ID1-ptbr"
File is different.

2021-07-08 15:24 UTC, RalphBragg commented on all-documents.md
> +7. deve manter registros sobre o histórico dos consentimentos para permitir a adequada formação de trilhas de auditoria em conformidade com a regulação em vigor;
Can these requirements be added to the security profile ID2.

2021-07-08 16:57 UTC, ediemerson-br requested changes

2021-07-08 16:57 UTC, ediemerson-br commented on all-documents.md
> +8. deve retornar falha na autenticação e o código de retorno _access_denied_ no parâmetro _erro_ (como especificado na seção 4.1.2.1 da RFC 6749) caso o CPF do usuário autenticado não seja o mesmo in
Change RFC 6749 to [RFC6749] in all documents.

2021-07-09 10:50 UTC, RalphBragg commented on open-banking-brasil-financial-api-1_ID2.md
> +* Marcos Rodrigues (Itaú)
Add your name @ginglass

2021-07-09 10:50 UTC, RalphBragg requested changes
Add your name please to the contributors section of the english specification.

2021-07-09 15:34 UTC, merged