Melhorias no Padrão de Certificados e correção do userinfo no TTP-PTbr
OpenBanking-Brasil/specs-seguranca pull request #187
Opened 2021-08-27 01:14 UTC by joaorodolfo

Atualização: IN99>>134, Ajustes no template de certificados, Inclusão da tabela de endpoint vs Tipos de Certificados / mTLS. Após aprovação e PR neste documento, deverá ser feita a atualização do documento na versão da língua Inglesa.

2021-08-28 00:43 UTC, ginglass commented on tpp-user-guide-ptbr.md
> +
typo?

2021-08-28 00:50 UTC, ginglass commented on tpp-user-guide-ptbr.md
> +
@joaorodolfo fiz um outro PR com esse conteúdo ajustado e outros requeridos recentemente. Minha sugestão é remover esse PR e incorporar só o outro, para evitar conflito no merge.

2021-08-28 00:51 UTC, ginglass requested changes
@joaorodolfo fiz um outro PR com esse conteúdo ajustado e outros requeridos recentemente. Minha sugestão é remover esse PR e incorporar só o outro, para evitar conflito no merge.

2021-08-30 18:22 UTC, joaorodolfo commented
It will be updated and changed by PR 188 (https://github.com/OpenBanking-Brasil/specs-seguranca/pull/188)
We can close it.

2021-08-30 18:24 UTC, joaorodolfo commented
> @joaorodolfo fiz um outro PR com esse conteúdo ajustado e outros requeridos recentemente. Minha sugestão é remover esse PR e incorporar só o outro, para evitar conflito no merge.

Podemos fechar esse PR e usar apenas o seu.

2021-08-30 18:24 UTC, closed without merging